version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql      

volumes:
  postgres: